language: ruby
bundler_args: --without development production
cache: bundler
sudo: false
rvm:
  - 2.3
jdk:
  - oraclejdk8
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
services:
  - redis-server
before_script:
  - cp ./config/secrets.yml.sample ./config/secrets.yml
  - RAILS_ENV=test bundle exec rake db:setup
  - RAILS_ENV=test bundle exec rake datarepo:add_roles
  - RAILS_ENV=test bundle exec rake jetty:clean
  - RAILS_ENV=test bundle exec rake sufia:jetty:config
  - RAILS_ENV=test bundle exec rake jetty:start
